
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 14 19:26:09 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 34;
  public static final int LBRACKET = 28;
  public static final int CONST = 15;
  public static final int CHAR = 17;
  public static final int EQUIVALENT = 39;
  public static final int GREATER = 36;
  public static final int LPAREN = 24;
  public static final int SEMI = 23;
  public static final int CONTINUE = 12;
  public static final int LESS = 35;
  public static final int MINUS = 33;
  public static final int STAR = 32;
  public static final int RPAREN = 25;
  public static final int AND = 42;
  public static final int NOT = 41;
  public static final int OR = 43;
  public static final int BOOL = 18;
  public static final int COMMA = 22;
  public static final int CLASS = 5;
  public static final int INC = 44;
  public static final int PLUS = 20;
  public static final int LESSEQ = 37;
  public static final int IF = 8;
  public static final int DOT = 30;
  public static final int FINDANY = 11;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 29;
  public static final int EQUAL = 21;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int NUMBER = 16;
  public static final int BREAK = 13;
  public static final int IDENT = 19;
  public static final int ARROW = 46;
  public static final int FOREACH = 10;
  public static final int LBRACE = 26;
  public static final int ELSE = 9;
  public static final int READ = 6;
  public static final int WHILE = 7;
  public static final int RBRACE = 27;
  public static final int PROG = 2;
  public static final int GREATEREQ = 38;
  public static final int DEC = 45;
  public static final int MODUL = 31;
  public static final int PRINT = 3;
  public static final int NOTEQ = 40;
}

